//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIS.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class feespayment
    {
        public int id { get; set; }
        public int semester_fee_id { get; set; }
        public int student_id { get; set; }
        public double amount { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual semesterfee semesterfee { get; set; }
        public virtual student student { get; set; }
    }
}
