//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIS.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class finaltran
    {
        public string name { get; set; }
        public System.DateTime DOB { get; set; }
        public string depart { get; set; }
        public string program { get; set; }
        public int requiredCredit { get; set; }
        public string code { get; set; }
        public string description { get; set; }
        public int student_id { get; set; }
        public string semesterName { get; set; }
        public string Grade { get; set; }
        public Nullable<double> gradepoint { get; set; }
    }
}
