//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIS.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class reportdata
    {
        public int student_id { get; set; }
        public int semesterCourse_id { get; set; }
        public string code { get; set; }
        public string description { get; set; }
        public string Grade { get; set; }
        public Nullable<double> gradepoint { get; set; }
        public Nullable<int> id { get; set; }
        public Nullable<int> course_id { get; set; }
        public Nullable<int> semester_id { get; set; }
        public string sem { get; set; }
    }
}
