//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIS.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class reportdemog
    {
        public int student_id { get; set; }
        public string fullname { get; set; }
        public System.DateTime DOB { get; set; }
        public string email { get; set; }
        public string Address { get; set; }
        public string program { get; set; }
        public System.DateTime admission_date { get; set; }
        public System.DateTime completion_date { get; set; }
        public string name { get; set; }
        public int requiredCredit { get; set; }
    }
}
