//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIS.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class semesterfee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public semesterfee()
        {
            this.feespayments = new HashSet<feespayment>();
        }
    
        public int id { get; set; }
        public int program_id { get; set; }
        public int semester_id { get; set; }
        public double amount { get; set; }
        public int student_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<feespayment> feespayments { get; set; }
        public virtual program program { get; set; }
        public virtual semester semester { get; set; }
        public virtual student student { get; set; }
    }
}
